### ISSUE TITLE
setup-files/terraform does not exist

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#11]
While setting up student virtual machine, there is requirements on following page:
http://localhost:4000/setting-up/setup-student-virtual-machine.html

**Recursively copy files from inside the terraform folder into the /home/student/terraform folder. You can use cp -r setup-files/terraform/* /home/student/terraform/ to do this.**

But there is no such folder as setup-files and there is no terraform folder.

**Comment by riyazwalikar** [comment]
The folder is present in the root of the repository. When you clone this repo, the folder is present in the root folder of the cloned content.

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/tree/master/setup-files

Closing this issue, please re-open if you need to add additional comments.
