### ISSUE TITLE
Getting error while running deploy-cloudhacker

### ISSUE THREAD

**Issue by hunter-practice** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#12]
While setting up the attacker machine in AWS by running deploy-cloudhacker script. I am getting error.

The error seems to be related with permission, so tried to run with sudo command but it's failing as well as it was suppose to be run as non root user.
<img width="900" alt="Screenshot 2020-05-25 at 3 58 50 PM" src="https://user-images.githubusercontent.com/60606845/82824164-b7925d00-9ea0-11ea-84a4-0f5779439dad.png">

**Comment by hunter-practice** [comment]
terraform version is Terraform v0.11.3

**Comment by hunter-practice** [comment]
I was trying in kali machine. Thought that might be causing the issue. So configured a new Ubuntu  VM. Got same error.

<img width="1287" alt="Screenshot 2020-05-25 at 11 25 47 PM" src="https://user-images.githubusercontent.com/60606845/82846086-12e34000-9edf-11ea-8c67-df0b7cb25478.png">
<img width="1164" alt="Screenshot 2020-05-25 at 11 26 07 PM" src="https://user-images.githubusercontent.com/60606845/82846093-1e366b80-9edf-11ea-958a-f3016b8a943d.png">

Previously i was seeing this error then i had gone and checked the script and found the terraform file and had ran "sudo terraform init" command within that directory. After that got the new error which was given in the 1st comment.

Not doing again this step in this VM.

**Comment by riyazwalikar** [comment]
Have you completed all the steps listed in the "Setting up and accessing the student virtual machine" chapter?

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/blob/master/documentation/setting-up/setup-student-virtual-machine.md

From the error messages it appears that some of the pre-reqs may not have been met. Can you confirm that all instructions in the chapter mentioned were followed?

**Comment by hunter-practice** [comment]
Yes i can confirm that i have gone through all the steps of Setting up and accessing the student virtual machine but still getting the error.

**Comment by riyazwalikar** [comment]
That is weird. Can you provide the following information so that this can be troubleshooted

1. Version of aws cli (`aws --version`)
2. Output of `ls -alh /usr/bin/deploy*`
3. Output of `ls -ltraR ~`

**Comment by hunter-practice** [comment]
<img width="773" alt="Screenshot 2020-06-01 at 12 03 22 PM" src="https://user-images.githubusercontent.com/60606845/83403240-35ee8200-a400-11ea-9a05-6a92ba9ec099.png">
<img width="727" alt="Screenshot 2020-06-01 at 12 03 52 PM" src="https://user-images.githubusercontent.com/60606845/83403246-38e97280-a400-11ea-9671-0a587436f928.png">
[output.txt](https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/files/4710892/output.txt)
Here are the results.

**Comment by riyazwalikar** [comment]
It appears that the `/home/student/terraform` folder was created using sudo and subsequently the copy command to copy files into this directory was also with sudo.

Can you recreate this folder or chown this directory and all files recursively as the `student` user?

**Comment by hunter-practice** [comment]
Thanks worked like a charm
