### ISSUE TITLE
where can i find ssh-checker?

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#13]
Hi,
"http://localhost:4000/setting-up/setting-up-and-accessing-the-attacker-vm.html " says to run "ssh-checker" on my ubuntu vm but i can't find such tool over the internet.

**Comment by riyazwalikar** [comment]
`ssh-checker` is a script we wrote for this training. You will not find it over the internet. Please make sure that you have followed all instructions listed in the "Setting up and accessing the student virtual machine" chapter.

The "steps-to-setup-the-student-virtual-machine" section in this chapter has the steps to copy the scripts to the virtual machine.

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/blob/master/documentation/setting-up/setup-student-virtual-machine.md#steps-to-setup-the-student-virtual-machine

**Comment by testacc0808** [comment]
Thanks
