### ISSUE TITLE
* provider.aws: error using credentials to get account ID: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature expired: 20200531T052050Z is now earlier than 20200531T052308Z (20200531T053808Z - 15 min.) 	status code: 403, request id:

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#14]
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: error using credentials to get account ID: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature expired: 20200531T052050Z is now earlier than 20200531T052308Z (20200531T053808Z - 15 min.)
	status code: 403, request id: 

Failed to load backend: This plan was created against an older state than is current. Please create
a new plan file against the latest state and try again.

Terraform doesn't allow you to run plans that were created from older
states since it doesn't properly represent the latest changes Terraform
may have made, and can result in unsafe behavior.

Plan Serial:    0
Current Serial: 2

**Comment by testacc0808** [comment]
Any comments?

**Comment by riyazwalikar** [comment]
This happens if there is a mismatch in the time between the student virtual machine and the server. To fix this, reset your student VMs clock to sync with the server. You can use the following commands on the student VM:

**If your timezone is India GMT +530**
```
sudo -i
echo -n Asia/Kolkata > /etc/timezone
rm /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
sudo service ntp stop
sudo ntpdate -s time.nist.gov
sudo service ntp start
````

**Comment by testacc0808** [comment]
Thank you!
