### ISSUE TITLE
identify your unique name that was generated earlier and is now in your bash prompt

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#16]
Hi,
I'm going through your training and faced an issue from following section:
http://localhost:4000/cloud-compute/application-misconfigurations.html  (Steps to create a DNS name for the app server)

It says "On the student VM, add a host file entry to point your system to a domain name for the web application. identify your unique name that was generated earlier and is now in your bash prompt " 

By unique name in bash prompts , do you mean hostname of cloudhacker machine? 

If you mean hostname of target machine (10.0.100.11). I ssh to target machine from cloudhacker. I tried to use hostname of target machine but it does not work as well

Thank you in advance/

**Comment by riyazwalikar** [comment]
The documentation at https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/blob/master/documentation/cloud-compute/application-misconfigurations.md has additional instructions to complete this. Please follow the instructions step by step in this section.

Your unique name will be printed in your bash prompt and when you executed the `aws-cli-access-checker` earlier in the training.

Examples of what the host entry will look like along with examples of what the unique name looks like are already covered in the documentation.

**Comment by testacc0808** [comment]
Thank you
