### ISSUE TITLE
Problem with passing the argument in URL for webhook-API

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#18]
Based on http://localhost:4000/bapazure/cloud-compute/azure-functions.html , 
Once you created "Webhook + API" , documentations says you need copy the URL from the modal window. After that , you need to navigate to the URL and pass a name=Test GET parameter at the end of the URL to execute the Function.
My URL is in the following format:
 https://hackme.azurewebsites.net/api/HttpTrigger2?code=9FiA0AFZ5Zro3e9BMa/JYP4KpsblraCwFhskrDOtSwVcsZc2Oe1Hw==

If i add that in the end of URL, it will give me an error " page can’t be found"

**Comment by riyazwalikar** [comment]
`name` is an additional GET parameter to the URL. You must separate two GET query parameters with an & as shown below

`https://url/api/HttpTrigger2?code=xxx&name=Test`

**Comment by testacc0808** [comment]
It works :) 
Thank you @riyazwalikar
