### ISSUE TITLE
Error: unknown command "internal" for "slurp"

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#19]
![image](https://user-images.githubusercontent.com/64963907/83949550-166bb500-a857-11ea-8dc7-bc53c0834d3c.png)

Does the installed slurp on cloudhacker really support the "internal" command?

*I have configured my aws profile under ~/.aws/credentials

**Comment by 0xbharath** [comment]
Good catch. The Slurp part was intended to be a demo. Slurp binary installed on cloudhacker is  v1.

Slurp v2 supports `internal` command and this is the version under active development. I have added the steps to download and run Slurp v2 with `internal` mode. 

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/pull/22

**Comment by riyazwalikar** [comment]
Closing this as the documentation is now updated.
