### ISSUE TITLE
Accessing the source of Lambda using stolen creds - no aws creds?

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#20]
Hi,
based on the guide "http://localhost:4000/cloud-compute/attacking-serverless-lambda-endpoints.html",  Lambda should have stored credentials aws credentials. 
I checked on ~/. aws/credentials  but there is nothing.
This is my request:
 curl "https://asd22sds3.execute-api.us-east-1.amazonaws.com/api/hack;cat%20~%2F.aws%2Fcredentials;w"

The guide says that when you have AWS creds you can access via "aws configure".
But i have only creds from /etc/passwd
There is no aws creds

**Comment by riyazwalikar** [comment]
The documentation does not say that.

The documentation says the following

> When AWS credentials are stolen and added to AWS CLI via `aws configure`, you can run the following commands to attempt a download of the lambda code itself. This is useful if you have managed to obtain credentials from a different user/role/temporary tokens etc. and would want to see what lambda functions are running in the target environment.

This is not talking about stealing credentials from lambda. It is about stealing in general (like the previous exercise using SSRF).

Lambda will have temporary tokens as well, which are present as environment variables and can be seen with the `printenv` command.

**Comment by testacc0808** [comment]
thank you
