### ISSUE TITLE
Can't add hostname for "Domain Takeover exercise"

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#21]
Hi,
I'm doing following exercise based on :
http://localhost:4000/bapazure/other-services/azure-app-services-subdomain-takeover.html

I stuck at the "Add a custom domain to the App Service" section on following step:
"2. Click on Add hostname and type XXXXXXXXXX.galaxybutter.co. Replace XXXXXXXXXX with your team name."

There is no hostname button.  I have add custom domain and getting an error on "domain ownership" section

![image](https://user-images.githubusercontent.com/64963907/84801746-22632e00-b032-11ea-986d-ba40d63e7153.png)

**Comment by testacc0808** [comment]
Hi sir,

any updates on this?

**Comment by riyazwalikar** [comment]
Use the `+ Add  custom domain` option to add a custom domain name.

In any case, this exercise will not work since we have released the training as we cannot create subdomains for everyone doing this section.

**Comment by testacc0808** [comment]
Noted. Thank you @riyazwalikar 

Would you reccomend any tutorial to practice subdomain takeover? when i can take a look at the entire process by creating domain etc..

**Comment by riyazwalikar** [comment]
I'm not aware of any tutorial that shows the entire process. However you can practice this by

1. Setting up your own domain with a Domain Name provider (Namecheap, Gandi, GoDaddy etc.)
2. Add a CNAME to a S3 bucket or an Azure app services endpoint to a subdomain for your Domain Name.
3. Create the S3 bucket or an Azure app with the same name as the CNAME in step 2.
