### ISSUE TITLE
SSH password for deploy-compute-target (EC2)

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#23]
Hi,

can you share ssh password for AWS EC2 that is be deployed using "deploy-compute-target" from cloudhacker.

I want to ssh to the machine to practice locally from that machine

**Comment by testacc0808** [comment]
Hi @riyazwalikar ,
 could you please help me on this? would really appreciate your help

**Comment by testacc0808** [comment]
Guys, i know the rdp password but i can't rdp to that machine as i do not have access from the student machine.  
There is no way to rdp from cloudhacker.. i guess i still need to use ssh..

**Comment by riyazwalikar** [comment]
The SSH password for AWS EC2 deployed using "deploy-compute-target" can be found using **Attack 2** from https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/blob/master/documentation/cloud-compute/attacking-ec2s-via-exposed-ports.md

**Comment by riyazwalikar** [comment]
Under **Attack 3 - Dictionary attack against RDP (Demo)** the documentation very clearly says the following

`This is a demo. This machine is NOT created using the deploy-compute-target. We set this up during the in-person training.`

This machine does not exist and is created when we deliver the training in person. You can create your own Windows Instance and set the password to the one in the image and practice the attack.

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/blob/master/documentation/cloud-compute/attacking-ec2s-via-exposed-ports.md
