### ISSUE TITLE
ERROR APPLYING PLAN | Not authorised for images [ ami-04580aa96a68a006c ]

### ISSUE THREAD

**Issue by lynxhead** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#28]
Getting this error of AMI  [ ami-04580aa96a68a006c ]
Status Code : 400

i checked available AMI's in AWS, but couldn't find anything with the above AMI Id.
 
![1](https://user-images.githubusercontent.com/51532557/203976234-e740ec59-3dd6-4cee-bf92-2b6492c56cdb.png)

**Comment by riyazwalikar** [comment]
The AMI permission has now been reset to public. The script should work now.
