### ISSUE TITLE
ami in all the scripts are not working.

### ISSUE THREAD

**Issue by sagarbanwa** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#29]
I was setting this application look like cloudhacker TF script and other script need to get updated there ami version 

example : 

ami = "ami-04580aa96a68a006c" <== line 130 in /setup-files/terraform/cloudhacker/setup)/cloudhacker.tf

other ami are also outdated not in used anymore 

please update the script.

plz fix SSH issue also change ami with different one but having other issue like ssh denied :/

**Comment by riyazwalikar** [comment]
Permission for the following AMIs have been fixed. They are now public, as required by the TF scripts.

- ami-04580aa96a68a006c
- ami-05a1c1724ec25d290
- ami-018983eec519a0fa9

**Comment by sagarbanwa** [comment]
Thanks working ... 

Nov-26-2022
