### ISSUE TITLE
deploy-awslambda always results in InternalServerError when interacting with the API

### ISSUE THREAD

**Issue by angrypapa** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#3]
After running `$ deploy-awslambda` and obtaining the Rest API URL I always get the following when I try to interact with it, instead of the expected md5sum.

```
$ curl "https://blabla.execute-api.us-east-1.amazonaws.com/api/hello"
{"Code":"InternalServerError","Message":"An internal server error occurred."}
```

Any idea?

**Comment by angrypapa** [comment]
Figure it out, had to change the environment to Python 2.7 in the web interface.

**Comment by testacc0808** [comment]
> Figure it out, had to change the environment to Python 2.7 in the web interface.

Hi,
 Can you tell me how did you access web interface?
I tried to check on following URL:
https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/discover
There is nothing related to web interface.
