### ISSUE TITLE
ERROR LAUNCHING SOURCE INSTANCE  [ ami-4f1ef332 ]

### ISSUE THREAD

**Issue by lynxhead** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#31]
WE Getting this error when running "deploy-compute-target"   in the Student VM.

[ ami-4f1ef332 ] 

![1](https://user-images.githubusercontent.com/51532557/204077131-f1a1c9e1-023a-47e5-a9e7-9cac04d058a5.png)

**Comment by riyazwalikar** [comment]
Try now.

**Comment by lynxhead** [comment]
WORKING NOW.
