### ISSUE TITLE
missing instructions for ff/burp config

### ISSUE THREAD

**Issue by kbb29** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#4]
somewhere around line 36, we need some instructions like:

```
Tell Firefox to use the Burp Proxy:

Preferences > General > Network Settings

Select "Manual proxy configuration"

HTTP Proxy : 127.0.0.1
Port: 8080

Click "OK"

```

**Comment by riyazwalikar** [comment]
Which file is this needed to be updated?

**Comment by kbb29** [comment]
Apologies.  This one:

documentation/cloud-compute/application-misconfigurations.md

**Comment by riyazwalikar** [comment]
Added. Check and close this issue, if the explanation is okay.
