### ISSUE TITLE
`deploy-cloudhacker` command fails with errors

### ISSUE THREAD

**Issue by riyazwalikar** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#6]
ubuntu @ adorable-street :$ deploy-cloudhacker 

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": failed to create plugin dir .terraform/plugins/linux_amd64: mkdir .terraform: permission denied.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.aws: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

_Originally posted by @D33van in https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/issues/5#issuecomment-616925127_

**Comment by riyazwalikar** [comment]
1. What is the version of Terraform in use
2. Were all the steps from  @`documentation/setting-up/setup-student-virtual-machine.md` followed?

**Comment by D33van** [comment]
yes I have followed all the steps as it is 

Steps to setup the student virtual machine
Step 1 - Adding scripts in /usr/bin
Copy all files from the bin folder to /usr/bin/
Make them executable using chmod +x filename
Step 2 - Adding terraform scripts in home directory
Create a hidden folder called terraform in the student user's home directory using mkdir terraform
Verify if the folder is created using ls -ltra /home/student/terraform
Recursively copy files from inside the terraform folder into the /home/student/terraform folder. You can use cp -r setup-files/terraform/* /home/student/terraform/ to do this.
Verify if the files have been copied using ls -ltra /home/student/terraform/

**Comment by riyazwalikar** [comment]
What is the version of Terraform in use

**Comment by D33van** [comment]
Terraform v0.11.3

**Comment by riyazwalikar** [comment]
Assuming you created a fresh virtual machine for this training, can you provide the output of 
1. `id`
2. `ls -ltraR ~`

**Comment by riyazwalikar** [comment]
Closing this after 10+ days of inactivity. @D33van please reopen in case the issue is not resolved. Thank you.
