### ISSUE TITLE
"deploy-cloudhacker" issue

### ISSUE THREAD

**Issue by gitmukeshsharma** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#7]
Hi,

I am getting below error when trying to run command "deploy-cloudhacker". Could you please help me. (Please find attached image)
![cloudhacker](https://user-images.githubusercontent.com/61911716/80119657-9c81b400-85a7-11ea-8ce5-56c3b4f4b37d.PNG)

**Comment by kbb29** [comment]
try running 

aws-cli-access-checker

This creates a new shell with the correct environment vars

then you can run

deploy-cloudhacker

etc.

**Comment by gitmukeshsharma** [comment]
Hi, I am still getting the error after running the command "aws-cli-access-checker"
![image](https://user-images.githubusercontent.com/61911716/80174417-354c1a00-8610-11ea-85e6-b1e68bbba16f.png)

**Comment by riyazwalikar** [comment]
What is the version of Terraform in use?

**Comment by gitmukeshsharma** [comment]
![image](https://user-images.githubusercontent.com/61911716/80175113-531a7e80-8612-11ea-9693-06ba3e9db74e.png)

**Comment by riyazwalikar** [comment]
There are some breaking changes between 0.11.X and 0.12.X of Terraform.

Remove Terraform and install v0.11.3 (tested version)

Steps to do this are in the documentation/setting-up/setup-student-virtual-machine.md.

Close this issue once resolved.

**Comment by gitmukeshsharma** [comment]
Hi, 
I have installed v0.11.11 and now some permission error is coming up.
![image](https://user-images.githubusercontent.com/61911716/80281180-feb4f300-8726-11ea-9e9f-08e36bbf93fb.png)

**Comment by riyazwalikar** [comment]
Is the file `/home/student/.ssh/id_rsa.pub` present? If not, the ssh-checker command was not run. 

Please follow the step by step instructions given in `documentation/setting-up/setup-student-virtual-machine.md`

Thank you.

**Comment by esrkrishna** [comment]
Hi Team,
I am getting error while deploying the AWSLamda
deploy-awslambda
![lamda](https://user-images.githubusercontent.com/37097377/80677976-958f0000-8ad7-11ea-8ac1-bbeed671f380.PNG)

**Comment by esrkrishna** [comment]
> Hi Team,
> I am getting error while deploying the AWSLamda
> deploy-awslambda
> ![lamda](https://user-images.githubusercontent.com/37097377/80677976-958f0000-8ad7-11ea-8ac1-bbeed671f380.PNG)

Resolved,
Thanks

**Comment by riyazwalikar** [comment]
Thank you. I'm closing this issue as this has been resolved.
