### ISSUE TITLE
chalice/python version complications

### ISSUE THREAD

**Issue by kbb29** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#8]
The current version of setup-files/bin/deploy-awslambda tries to deploy a python2 compatible lamda function to AWS.  Chalice uses the version of python under which it is running to determine what runtime the lambda should use.  So if you are running chalice under python v2, all is good (the lambda will execute in a v2 runtime).  If you are running chalice under python v3 it will deploy the lambda with a v3 runtime, which is incompatible with the lambda code.

So either:

update setup-files/terraform/cloudlambda/md5sum/app.py to python v3
    and
add "pip3 install chalice" to documentation/setting-up/setup-student-virtual-machine.md

OR

leave the code as python v2
   and
add "sudo apt install python-pip" and "pip2 install chalice"  to documentation/setting-up/setup-student-virtual-machine.md

**Comment by makash** [comment]
Hi, 

Could you make a PR for this change to python v?

**Comment by kbb29** [comment]
done

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/pull/10

**Comment by riyazwalikar** [comment]
PR accepted. Merge complete. Thanks!
